spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: false
  flyway:
    placeholders:
      onUpdateClause: ON UPDATE CURRENT_TIMESTAMP

logging:
  level:
    org:
      springframework:
        security: DEBUG